#+TITLE: terraform-oci-minecraft

Based on [[https://github.com/RhubarbSin/terraform-oci-free-compute-maximal-example][RhubarbSin/terraform-oci-free-compute-maximal-example]].

Warning - this is created by someone with no previous Terraform experience. I just wanted to get it up and running as quickly as possible.

* What it is
  A Terraform configuration for compute resources on the Free Tier of Oracle Cloud Infrastructure.
* What it does
  Deploy two Always Free ARM instances for hosting Minecraft servers.
* How to use it
  For simplicity — to avoid the need to install and configure Terraform and the OCI CLI — this configuration is designed for deployment as a stack in the OCI Resource Manager.
  1. Pack this folder into a ZIP file.
  2. Log into the Oracle Cloud Infrastructure Console.
  3. Go to the Resource Manager: from the hamburger menu on the upper left, find *Developer Services* → *Resource Manager* and select *Stacks*.
  4. Click on the *Create Stack* button, select *.zip file* under *Stack Configuration* and select the file via the *Browse* link.
  5. Click on the *Next* button and provide an SSH public key.
  6. Click *Next* again and then *Create*.
  7. Click on the *Plan* button and start the plan job by clicking *Plan* again.
  8. After the plan job completes, from the *Resource Manager* » *Stacks* » *Stack Details* » *Job Details* page go to *Resource Manager* » *Stacks* » *Stack Details*.
  9. Click on the *Apply* button and start the apply job by clicking *Apply* again.
  10. After the apply job completes, from the hamburger menu find *Compute* → *Compute* and select *Instances*. Select the newly created compartment (named /OCI-Free-Minecraft/ by default) from the *Compartment* menu.
  11. Information for connecting to the instances with SSH can be found by selecting an instance and viewing the details under *Instance access* on the *Instance information* tab.
  12. To destroy the resources, navigate back to *Resource Manager* » *Stacks* » *Stack Details* and click on the *Destroy* button and click *Destroy* again.
  13. To delete the stack, after the destroy job completes, from the *Resource Manager* » *Stacks* » *Stack Details* » *Job Details* page go to *Resource Manager* » *Stacks* » *Stack Details*. From the *More Actions* menu choose *Delete Stack* and then *Delete*.
* Details
  - The resources deployed include the following:
    + One (1) Compartment
    + One (1) Virtual Cloud Network
    + One (1) Internet Gateway
    + One (1) Subnet
    + One (1) Network Security Group
    + One (1) A1 Flex instance running the latest Oracle Linux distribution with the following specifications:
      - 3 OCPUs
      - 18 GiB of memory
      - 50 GiB of storage
      - 1 reserved public IP address
    + One (1) A1 Flex instance running the latest Oracle Linux distribution with the following specifications:
      - 1 OCPUs
      - 6 GiB of memory
      - 50 GiB of storage
      - 1 ephemeral public IP address
    + Two (2) volume backup policies that will create a backup of each boot volume on a daily basis and retain the backup for two days (due to the limitation of five volume backups)
  - The default security list that is explicitly associated with the subnet allows inbound traffic to ports 22 and 25565 from any origin and all outbound traffic to any destination.
  - The network security group associated with the instances' VNICs allows inbound ICMP echo (i.e. ping) traffic from any origin and all outbound traffic to any destination.
