# Your database type
# MySQL is also compatible with MariaDB
# Databases supported: MySQL
db_type: 'mysql'
# The address of your database (can be 'localhost')
db_host: 'localhost'
# The port that your database uses
db_port: 3306
# The database name you want to use (the database should already exist)
db_name: 'minecraft_db'
# Do you want to use SSL when connecting to the database?
db_ssl: false
# The username used for connection to the database
db_user: 'minecraft_user'
# The password used for connection to the database
db_password: 'your_password'
# The table you want to use (will be created automatically if it doesn't exist)
# Please note that for ID generation, a second table with '_sequence' suffix will be created
table_name: 'simple_notepad'
# How many concurrent connections can the plugin make?
db_connections: 10
# Do you want to automatically regenerate Hibernate's configuration when loading the plugin?
# Useful for debugging Hibernate
regenerate_hibernate_config: true
