name: 'SimpleNotepad'
version: '0.1'
main: 'io.github.darkognu.simplenotepad.SimpleNotepad'
api-version: '1.19'
libraries:
  - 'org.hibernate.orm:hibernate-core:6.1.5.Final'
commands:
  notepad:
    description: 'Your personal notepad'
    usage: '/notepad [new | list | search | delete]'
    permission: 'simplenotepad.general'
